### ISSUE TITLE
`nodemon` with `pstree.remy@1.1.2` leaving an orphaned process running after restarts

### ISSUE THREAD

**Issue by chrisguidry** [remy/pstree#4]
Hi!  We are using a local development workflow with Docker where we use `nodemon` (`@1.18.6`) to monitor files for changes and restart a `babel-node` server.

On versions of `pstree.remy` <= 1.1.0, everything works as expected.

On version 1.1.1, we get this error:
```
web_1     | [frontend] [nodemon] restarting due to changes...
web_1     | [frontend] /node_modules/nodemon/lib/monitor/run.js:336
web_1     | [frontend]         spawn('kill', ['-s', sig, child.pid].concat(kids.map(p => p.PID)))
web_1     | [frontend]                                                          ^
web_1     | [frontend] 
web_1     | [frontend] TypeError: Cannot read property 'map' of undefined
web_1     | [frontend]     at /node_modules/nodemon/lib/monitor/run.js:336:58
web_1     | [frontend]     at /node_modules/pstree.remy/lib/tree.js:53:11
web_1     | [frontend]     at ChildProcess.onClose (/node_modules/pstree.remy/lib/tree.js:80:9)
web_1     | [frontend]     at ChildProcess.emit (events.js:180:13)
web_1     | [frontend]     at maybeClose (internal/child_process.js:936:16)
web_1     | [frontend]     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

On version 1.1.2, we don't get an error, but we see that the previous server is orphaned in the container (perhaps `pstree.remy` wasn't able to report that it was a child to `nodemon`?)  This causes at least one major issue for us, because the port the orphaned server is listening on isn't closed.

**Comment by chrisguidry** [comment]
Also, sorry I don't have an example of a simplified test case that reproduces the issue.  It's very possible the issue is on the `nodemon` side.
